codemagic file updated with internal testing

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -239,31 +239,36 @@ workflows:
           include: true
           source: true
     scripts:
-      #- name: Get Code Artifact Token
-        #script: | 
-          #export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ui-libs --domain-owner 292474393014 --query authorizationToken --output text`
-          #aws codeartifact login --tool npm --repository ui-library --domain ui-libs --domain-owner 292474393014 --region ap-south-1
-      - name: Install npm dependencies for Ionic Capacito project
+      - name: Check Versions
+        script: |        
+          node -v
+          npm --version
+          ionic version
+      - name: Get AWS Code Artifact Token
         script: |
           #echo $AWS_DEFAULT_REGION_HOLDER
           #aws --version
           #aws ls
-          ionic version
           #echo "hello world"
           #aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID_HOLDER"
           #aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY_HOLDER"
           #aws configure set region "$AWS_DEFAULT_REGION_HOLDER"
           #aws configure set output "json"
-          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ui-libs --domain-owner 292474393014 --query authorizationToken --output text`
+          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ui-libs --domain-owner 292474393014 --region ap-south-1 --query authorizationToken --output text`
           aws codeartifact login --tool npm --repository ui-library --domain ui-libs --domain-owner 292474393014 --region ap-south-1
           #echo "kunal"
-          echo $CODEARTIFACT_AUTH_TOKEN
+          # echo $CODEARTIFACT_AUTH_TOKEN
           npm config set registry=https://ui-libs-292474393014.d.codeartifact.ap-south-1.amazonaws.com/npm/ui-library/
           npm config set //ui-libs-292474393014.d.codeartifact.ap-south-1.amazonaws.com/npm/ui-library/:_authToken=${CODEARTIFACT_AUTH_TOKEN}
           #npm config set //ui-libs-292474393014.d.codeartifact.ap-south-1.amazonaws.com/npm/ui-library/:always-auth=true 
+          # npm config set registry=https://ui-libs-292474393014.d.codeartifact.ap-south-1.amazonaws.com/npm/ui-core/
+          # npm config set //ui-libs-292474393014.d.codeartifact.ap-south-1.amazonaws.com/npm/ui-core/:_authToken=${CODEARTIFACT_AUTH_TOKEN}
           npm config get registry
-          
-          npm install
+      - name: Install npm dependencies
+        script: |          
+          # npm install
+          # npm cache clean -f
+          npm ci
       - name: Set Android SDK location
         script: |
           echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
@@ -273,22 +278,41 @@ workflows:
           ionic build --prod # <- For production environment
           # ionic build # <- For Test environment
           npx cap sync # <- update native dependencies and copy web assets to native project
-          ls -lrt android/app
-          ls -lrt android/app/build
-          ls -lrt android/app/build/output
-          ls -lrt android/app/build/outputs/**/*.apk
-          ls -lrt android/app/build/**/release/**
-          APK_PATH=$(android/app/build/**/release/** -name "*.aab" | head -1)
-          jarsigner \
-           -sigalg SHA1withRSA \
-           -digestalg SHA1 \
-           -keystore $CM_KEYSTORE_PATH \
-           -storepass $CM_KEYSTORE_PASSWORD \
-           -keypass $CM_KEY_PASSWORD \
-           $APK_PATH $CM_KEY_ALIAS
+      - name: Build Android release
+        script: |
+          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+          if [ -z LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
+            # fallback in case no build number was found from Google Play.
+            # Alternatively, you can `exit 1` to fail the build
+            # BUILD_NUMBER is a Codemagic built-in variable tracking the number
+            # of times this workflow has been built
+            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+            echo $UPDATED_BUILD_NUMBER
+            echo $BUILD_NUMBER
+          else
+            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+            echo $UPDATED_BUILD_NUMBER
+            echo $LATEST_GOOGLE_PLAY_BUILD_NUMBER
+          fi
+          cd android
+            chmod +x gradlew
+          #./gradlew bundleRelease # -> to create the .aab and #./gradlew assembleRelease # -> to create the .apk
+          ./gradlew bundleRelease \
+            -PversionCode=$UPDATED_BUILD_NUMBER \
+            -PversionName=1.0.$UPDATED_BUILD_NUMBER
+      - name: Signing key.properties
+        script: |
+          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
+          storePassword=$CM_KEYSTORE_PASSWORD
+          keyPassword=$CM_KEY_PASSWORD
+          keyAlias=$CM_KEY_ALIAS
+          storeFile=$CM_KEYSTORE_PATH
+          EOF
     artifacts:
-      #- android/app/build/outputs/**/*.apk
-      - android/app/build/**/release/**/*.aab
+      - android/app/release/*.aab
+      - android/app/build/outputs/**/*.aab
+      - android/app/release/*.apk
+      - android/app/build/outputs/**/*.apk
     publishing:
       email:
         recipients:
